class_name SharedCardsData
## Cards used by multiple heroes or as generic tokens
##
## These cards can appear in multiple character decks or are generated
## as tokens during gameplay.

const CARDS = {
	# === SHARED REWARD/UTILITY CARDS ===
	"energy": {
		"card_name": "Energy!",
		"description": "Plays instantly. Gain 1 stamina. TARGET: Self.",
		"card_type": "BUFF",
		"target_type": "SELF",
		"stamina_cost": 0,
		"stamina_gain": 1,
		"plays_immediately": true
	},

	# === TOKEN CARDS ===
	"ember": {
		"card_name": "Ember",
		"description": "Deal 4 damage. TOKEN.",
		"card_type": "ATTACK",
		"target_type": "SINGLE_ENEMY",
		"stamina_cost": 0,
		"damage": 4
	}
}

## Cards available to add to any hero's reward pool
const SHARED_REWARD_CARDS = ["energy"]

## Token cards that can be generated by other cards
const TOKEN_CARDS = ["ember"]
